### ISSUE TITLE
4K Video Downloader not opening...

### ISSUE THREAD

**Issue by Rit1X1** [EvertonCosmo/ArchLinuxPackages#1]
I installed 4kvideodownloader  4.9.0.3032-1 from "AUR" through pamac-manager in manjaro kde.
But when i tried to open, it's icon just flashed for a second in panel and then disappear. I am quite new to arch linux based system. So, please kindly help me...

**Comment by EvertonCosmo** [comment]
Hi, @Rit1X1 did you successfully install  ?
You can just download this repository and use it
Running **makepkg -sri**
